config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :comments, except: [:index, :show]
    resources :answers, except: [:index, :show]
    member do
      post 'vote'
    end
  end
  resources :answers, except: [:index, :show] do
    member do
      put 'update_best_answer'
    end
    resources :comments, except: [:index, :show]
    member do
      post 'vote'
    end
  end

  resources :users, :sessions

  get 'welcome/index'
  get 'search', to:'welcome#search', as: :search
  get 'login', to: 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup', to: 'users#new', as: :signup
  post 'signup' => 'users#create'
  root 'welcome#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
  after_create :default_vote

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates_presence_of :title, :body

  def default_vote
    vote = self.votes.build(vote_count:0)
    vote.user = self.user
    vote.save
  end

  def vote_count
    votes.sum(:vote_count)
  end

  def answers_by_votes
    answers.where(best_answer: false).sort{|ans1, ans2| ans2.vote_count <=> ans1.vote_count}
  end

  def best_answer
    answers.where(best_answer: true).first
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_login, :except => [:index, :show]

  def index
     @question_votes =  Vote.where(votable_type: 'Question').group(:votable_id).sum(:vote_count)
    if params[:order]
      @questions = Question.order(updated_at: :desc)
      render :index_chrono
    else
      @questions = Question.joins(:votes).group(:id).order('SUM(votes.vote_count) DESC')
      render :index
    end
  end

  def show
    @question = Question.includes(:comments, :answers ).find_by(id: params[:id])  
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = found_question
  end

  def update
    @question = found_question
    if @question.update_attributes(question_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question = found_question
    if @question.user_id == session[:user_id]
      @question.destroy
      redirect_to questions_path
    else
      redirect_to login_path
    end
  end

  def vote
    @question = found_question
    vote = Vote.create(vote_count: params[:vote_count], user: current_user, votable: @question)
    if vote.valid?
      flash[:notice] = "You voted"
    else
      flash[:error] = "You cannot vote more than once"
    end
    redirect_to :back
  end

  private

  def found_question
    Question.find_by(id: params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div id = 'error_explanation'>
      <h2>
        <%= pluralize(@question.errors.count,'error') %> Prohibited this Question from saving:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/_question.html.erb
<h1><%= question.title %></h1>

<%= link_to vote_question_path(question, vote_count: 1), method: 'post' do %>
  &#9650;
<% end %>
<%= question_votes[question.id] %>
<%= link_to vote_question_path(question, vote_count: -1), method: 'post' do %>
  &#9660;
<% end %>

<%= question.body  %>

<%= link_to "Asked by #{question.user.username}", user_path(question.user) %>
<div> <%= question.my_time %> </div>
<div>
  <%= link_to 'Edit Question', edit_question_path(question) %>
  <%= link_to 'Delete Question', question_path(question), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

<% if comments %>
  <% comments.each do |comment| %>
    <%= render partial: 'comments/comment', locals: {comment: c} %>
  <% end %>
<% end %>

<div><%= link_to 'Add a Comment', new_question_comment_path(@question) %></div>
<div><%= link_to 'Add an Answer', new_question_answer_path(@question) %></div>

app/views/questions/_stats.html.erb
<div class="stats">
  <ul>
    <li><%=votes[q.id]%><span>votes</span></li>
    <li><%= q.answers.length%><span>answers</span></li>
    <li><%= q.comments.length %><span>comments</span></li>
   </ul>
</div>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
 <%= render 'form' %>
 <%= link_to "back", questions_path %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<h3><%= link_to 'Ask a Question', new_question_path %></h3>
<%= link_to 'Sort by Newest Questions First', questions_path(order: "chronologically") %>
<% if @questions %>
 <%=render @questions %>
<% end %>

app/views/questions/index_chrono.html.erb
<h1>All Questions</h1>
<%= link_to 'Sort by Most Votes', questions_path %>
<% if @questions %>
   <%=render 'questions'%>
<% end %>

<button><%= link_to 'Ask a Question', new_question_path %></button>

app/views/questions/new.html.erb
<h1>New post</h1>

<%=render 'form'%>
<%= link_to 'back', questions_path%>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<%= render partial: 'application/votable', locals: {votable_object: @question} %>

<%= @question.body  %>
<%= link_to "Asked by #{@question.user.username}", user_path(@question.user) %>
<div> <%= pirate_time( @question.created_at ) %> </div>

<div>
  <%= link_to 'Edit Question', edit_question_path(@question) %>
  <%= link_to 'Delete Question', question_path(@question), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

<% if @question.comments %>
  <ul>
    <%= render partial: @question.comments %>
  </ul>
<% end %>

<div><%= link_to 'Add a Comment', new_question_comment_path(@question) %></div>
<div><%= link_to 'Add an Answer', new_question_answer_path(@question) %></div>

<h2>Answers:</h2>
<% if @question.best_answer %>
  <h4>Best Answer: </h4>
  <%= render partial: @question.best_answer  %>
<% end %>

<% if @question.answers_by_votes %>
  <h4>Other Answers: </h4>
  <%= render partial: @question.answers_by_votes %>
<% end %>

<div><%= link_to 'All Questions', questions_path %></div>