config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :comments, except: [:index, :show]
    resources :answers, except: [:index, :show]
    member do
      post 'vote'
    end
  end
  resources :answers, except: [:index, :show] do
    member do
      put 'update_best_answer'
    end
    resources :comments, except: [:index, :show]
    member do
      post 'vote'
    end
  end

  resources :users, :sessions

  get 'welcome/index'
  get 'search', to:'welcome#search', as: :search
  get 'login', to: 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup', to: 'users#new', as: :signup
  post 'signup' => 'users#create'
  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
   @questions =Question.all
   @question_votes =  Vote.where(votable_type: 'Question').group(:votable_id).sum(:vote_count)
  end

  def search
    @questions = Question.search(params[:search])
  end

end

app/views/welcome/_footer.html.erb
<!--<div class="wrapper-for-content-outside-of-footer">
   Uncomment this whole section for a sticky footer. The content of the page should be inside of this .wrapper-for-content-outside-of-footer
</div>-->

<footer class="footer-2" role="contentinfo">
  <div class="footer-logo">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image">
  </div>
    <ul>
      <li><a href="javascript:void(0)">Pirates</a></li>
     </ul>

    <div class="footer-secondary-links">
      <ul>
        <li><a href="javascript:void(0)">Terms and Conditions</a></li>
        <li><a href="javascript:void(0)">Privacy Policy</a></li>
      </ul>

      <ul class="footer-social">
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png" alt="Facebook">
          </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png" alt="Twitter">
        </a></li>
        <li><a href="javascript:void(0)">
          <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png" alt="YouTube">
        </a></li>
      </ul>
    </div>
</footer>

app/views/welcome/_hero.html.erb
<div class="hero">
  <div class="hero-inner">

    <a href="" class="hero-logo"> <%= image_tag "ship.gif" %>
</a>
    <div class="hero-copy">
      <h1>Welcome Hacker Pirates!</h1>
      <p>We have Tons Of Tech Treasure To Be Found!</p>
    </div>
  </div>
</div>

app/views/welcome/_navbar.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">

        <% if session[:user_id] %>
          <li class="nav-link"><a href="javascript:void(0)"><%= link_to('Logout', logout_path, :method => :delete) %></a></li>
        <% else %>
          <li class="nav-link"><a href="javascript:void(0)"><%= link_to('Login', login_path)%></a></li>
          <li class="nav-link"><a href="javascript:void(0)"><%= link_to('Signup', signup_path)%></a></li>
        <% end %>
      </ul>
        </li>
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <form role="search">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        </form>
      </div>
    </div>
  </div>
</header>

app/views/welcome/_questions.html.erb
<% @questions.each do |q| %>
<div class="comment">
  <div class="comment-content">
    <% @q = q%>
    <% @votes = @question_votes%>
    <%= render partial: 'stats', locals:{q:@q ,votes:@votes} %>
    <%= link_to("#{q.title}", question_path(q))%>
    </div>
</div>
<%end%>

app/views/welcome/_stats.html.erb
<div class="stats">
  <ul>
    <li><%=votes[q.id]%><span>votes</span></li>
    <li><%= q.answers.length%><span>answers</span></li>
    <li><%= q.comments.length %><span>comments</span></li>
   </ul>
</div>

app/views/welcome/index.html.erb
<h1 class="title">Pirate Overflow</h1>
<%= render 'hero' %>
<%=render  'questions' %>
<%= render 'footer'   %>

app/views/welcome/search.html.erb
<%= render @questions %>

app/views/welcome/show.html.erb
<% @questions.each do |q| %>
<div class="comment_questions" >
  <div class="comment-content">
    <% @q = q%>
    <% @votes = @question_votes%>
    <%= render partial: 'stats', locals:{q:@q ,votes:@votes} %>
    <%= link_to("#{q.title}", question_path(q))%>
    </div>
</div>
<%end%>