config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :comments, except: [:index, :show]
    resources :answers, except: [:index, :show]
    member do
      post 'vote'
    end
  end
  resources :answers, except: [:index, :show] do
    member do
      put 'update_best_answer'
    end
    resources :comments, except: [:index, :show]
    member do
      post 'vote'
    end
  end

  resources :users, :sessions

  get 'welcome/index'
  get 'search', to:'welcome#search', as: :search
  get 'login', to: 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup', to: 'users#new', as: :signup
  post 'signup' => 'users#create'
  root 'welcome#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  after_create :default_vote
  belongs_to :user
  belongs_to :question
  has_many :votes, as: :votable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true
  validates_uniqueness_of :only_one_best_answer, if: :only_one_best_answer

  def default_vote
    vote = self.votes.build(vote_count:0)
    vote.user = self.user
    vote.save
  end

  def vote_count
    votes.sum(:vote_count)
  end

  private

  def only_one_best_answer
    if best_answer == true && Answer.find_by(best_answer: true) == true
      errors[:name] = 'There is already a best answer'
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_login

  def new
    @question = Question.find_by(id: params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find_by(id: params[:question_id])
    @answer = @question.answers.build(answers_params)
    @answer.user = current_user
    if @answer.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    @answer = found_answer
    @question = @answer.question
  end

  def update
    @answer = found_answer
    @question = @answer.question
    @answer.update(answers_params)
    if @answer.save
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @answer = found_answer
    @question = @answer.question
    @answer.destroy
    redirect_to question_path(@question)
  end

  def vote
    @answer = found_answer
    vote = Vote.create(vote_count: params[:vote_count], user: current_user, votable: @answer)
    if vote.valid?
      flash[:notice] = "You voted"
    else
      flash[:error] = "You cannot vote more than once"
    end
    redirect_to :back
  end

  def update_best_answer
    @answer = found_answer
    @answer.best_answer = true
    if @answer.save
      redirect_to :back
    else
      flash[:error] = "There was an error"
      redirect_to :back
    end
  end

  private

  def found_answer
    Answer.find_by(id: params[:id])
  end

  def answers_params
    params.require(:answer).permit(:body, :user_id)
  end
end

app/views/answers/_answer.html.erb
<% if answer.question.user == current_user  && !answer.question.best_answer %>
  <%= link_to 'Mark as Best Answer', update_best_answer_answer_path(answer, best_answer: true), method: 'put'%>
<% end %>

<%= render partial: 'application/votable', locals: {votable_object: answer} %>
<%= answer.body %>
<%= link_to "Answered by #{answer.user.username}", user_path(answer.user) %>

<div> <%= pirate_time(answer.created_at)%> </div>

<div>
  <%= link_to 'Edit', edit_question_answer_path(answer.question, answer) %>
  <%= link_to 'Delete', question_answer_path(answer.question, answer), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

<% if answer.comments %>
  <ul>
      <%= render partial: answer.comments %>
  </ul>
<% end %>

<div><%= link_to 'Add a Comment', new_answer_comment_path(answer) %></div>

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@answer.errors.count, "error") %> prohibited this answer from saving:
      </h2>
      <ul>
        <% @answer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>
<%= render 'form' %>
<%= link_to 'Back', question_path(@question) %>

app/views/answers/new.html.erb
<h1>Submit a New Answer</h1>
<%= render 'form' %>
<%= link_to 'Back', question_path(@question) %>