config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :comments, except: [:index, :show]
    resources :answers, except: [:index, :show]
    member do
      post 'vote'
    end
  end
  resources :answers, except: [:index, :show] do
    member do
      put 'update_best_answer'
    end
    resources :comments, except: [:index, :show]
    member do
      post 'vote'
    end
  end

  resources :users, :sessions

  get 'welcome/index'
  get 'search', to:'welcome#search', as: :search
  get 'login', to: 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup', to: 'users#new', as: :signup
  post 'signup' => 'users#create'
  root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user !=nil
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in do this action"
      redirect_to login_url 
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def pirate_time( datetime )
    datetime.strftime("%B %d, %Y")
  end
end

app/views/application/_navbar.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <%= image_tag "ship.gif" %>
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><a href="javascript:void(0)"><%= link_to('Home', root_path) %></a></li>
        <% if session[:user_id] %>
          <li class="nav-link"><a href="javascript:void(0)"><%= link_to('Profile', user_path(session[:user_id])) %></a></li>
          <li class="nav-link"><a href="javascript:void(0)"><%= link_to('Logout', logout_path, :method => :delete) %></a></li>
        <% else %>
          <li class="nav-link"><a href="javascript:void(0)"><%= link_to('Login', login_path)%></a></li>
          <li class="nav-link"><a href="javascript:void(0)"><%= link_to('Signup', signup_path)%></a></li>
        <% end %>
      </ul>
        </li>
      </ul>
    </nav>
    <div class="navigation-tools">
      <div class="search-bar">
        <%= form_tag("/search", method: "get" ) do %>
          <%= label_tag( :search, "Search for:") %>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/application/_votable.html.erb
<% path = -> (obj, vote ){ votable_object.class == Question ? vote_question_path(obj,vote) : vote_answer_path(obj,vote) }%>

<%= link_to path.call( votable_object, vote_count: 1 ), method: 'post' do %>
  &#9650;
<% end %>
<%= votable_object.vote_count %>
<%= link_to vote_question_path(votable_object, vote_count: -1), method: 'post' do %>
  &#9660;
<% end %>